http:
  port: 8737
admin:
  port: 9878
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'

  comments_kanban_api:
    host: localhost
    methods: 'GET,POST,PATCH,DELETE' 
    paths: ['/comments/*', '/comments']

  kanban_api:
    host: localhost
    methods: 'GET,POST,PATCH,DELETE' 
    paths: ['/boards/*', '/tasks/*', '/boards', '/tasks']

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  kanban:
    url: 'http://kanban_kanbanapp_1:1747'
  comments-kanban:
    url: 'http://comments-kanban_comments_1:8835'
policies:
  - basic-auth
  - cors #:
      #- action:
          #origin: "*"
          #methods: "GET,PATCH,POST,DELETE"
          #allowedHeaders: "*"
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true

  service-kanban:
    apiEndpoints:
      - kanban_api
    policies:
      - proxy:
          - action:
              serviceEndpoint: kanban 
              changeOrigin: true

  service-comments-kanban:
    apiEndpoints:
      - comments_kanban_api
    policies:
      - proxy:
          - action:
              serviceEndpoint: comments-kanban 
              changeOrigin: true  
