version: '3.3'

services: 
    kanban_gateway:
        image: kanban-gateway
        build: 
            context: .
        ports: 
            - "${PORT}:8737"
            - "${SND_PORT}:9878"
        networks:
            - kanban

    rabbit-mq:
        image: rabbitmq:3-management
        hostname: ${HOSTNAME}
        ports: 
            - "${RABBITMQ_FST_PORT}:15672"
            - "${RABBITMQ_SND_PORT}:5672"
        networks:
            - kanban

networks:
  kanban:
      driver: overlay
      attachable: true
